openapi: 3.0.3
info:
  title: SubscriptionStatus
  description: |
    This API allows users to obtain the current subscription status of a phone number, including Voice/SMS inbound, Voice/SMS outbound, and data service status.

    # Introduction

    This API obtains the business subscription status of a phone number by passing it in, including Voice/SMS inbound, Voice/SMS outbound, and data service status.

    Normally, the business subscription status is active, and the following situations may lead to abnormal business subscription status.

    **Overdue fees and downtime**: If the account balance is insufficient or the monthly rental fee is not paid on time, the operator may suspend the service.

    **Real name authentication issue**: If identity information is not updated in a timely manner (such as expired documents or incomplete second real name authentication), the operator may freeze the account.

    **Violation**: Frequent making harassing phone calls, engaging in illegal activities, and other behaviors can lead to service suspension.

    **Abnormal usage behavior**: High frequency outgoing calls, long-distance roaming, sensitive period communication, and other behaviors may be detected by the operator's risk control system, which may lead to service suspension.

    It helps verify whether telecommunication services are active or suspended for fraud prevention, customer support, and operational checks.

    **Scenario 1 - Payment System Validation**:
      * A financial service provider uses this API to validate if a user's phone number has active voice/SMS services before processing high-risk transactions. If the API returns "suspended" for Voice/SMS inbound, the transaction is flagged for manual review to prevent fraud or invalid transfers.

    **Scenario 2 - Customer Service Troubleshooting**:
      * The user reported that they were unable to receive calls. Customer support queries the API and identifies that "Voice/SMS inbound" is suspended.
      * The user reported that they were unable to make a phone call. Customer support queries API and confirms that 'voice/SMS outbound' is suspended
      * The user reported that they are unable to use the data service.Customer support queries API and confirms that 'data service status' is suspended

      The customer service personnel guides the user to reactivate the service, resolving the issue.

    # Relevant terms and definitions
    - **Voice/SMS Inbound**
      Indicates the ability of the subscriber to **receive** incoming voice calls and SMS messages.
      - `active`: The subscriber can receive calls and SMS normally.
      - `suspended`: The subscriber is blocked from receiving calls/SMS (e.g., due to account suspension).

    - **Voice/SMS Outbound**
      Indicates the ability of the subscriber to **initiate** outgoing voice calls and send SMS messages.
      - `active`: The subscriber can make calls and send SMS normally.
      - `suspended`: The subscriber is blocked from initiating calls/SMS (e.g., due to unpaid bills or fraud restrictions).

    - **Data Service Status**
      Indicates the availability and performance level of mobile data connectivity.
      - `active`: Full-speed data access is enabled.
      - `suspended`: Data service is completely disabled (e.g., due to contract expiration).
      - `throttled`: Data service is available but speed is reduced (e.g., after exceeding usage limits).

    # Identifying the phoneNumber from the access token

    This API requires the API consumer to identify a phoneNumber as the subject of the API as follows:
    - When the API is invoked using a two-legged access token, the subject will be identified from the optional phoneNumber field, which therefore MUST be provided.
    - When a three-legged access token is used, the subject will be uniquely identified from the access token. So, the optional phoneNumber is not used for identifying the subject, but, if it is provided in the API request body, it needs to match with the one associated with the access token.

    ## Error handling:

    - If the subject cannot be identified from the access token and the optional phoneNumber field is not included in the request, then the server will return an error with the `422 MISSING_IDENTIFIER` error code. This is an error typically, but not uniquely, returned in 2-legged scenarios when the access token doesn't identify a single subscription.
    - If there is a mismatch between the provided phone number in the request body and the phone number associated with the access token, the server will return an error with the `403 INVALID_TOKEN_CONTEXT` error code.

    ### Additional CAMARA error responses
    The list of error codes in this API specification is not exhaustive. Therefore the API specification may not document some non-mandatory error statuses as indicated in `CAMARA API Design Guide`.
    Please refer to the `CAMARA_common.yaml` of the Commonalities Release associated to this API version for a complete list of error responses. The applicable Commonalities Release can be identified in the `API Readiness Checklist` document associated to this API version.
    As a specific rule, error `501 - NOT_IMPLEMENTED` can be only a possible error response if it is explicitly documented in the API.

    # Authorization and authentication
    The "Camara Security and Interoperability Profile" provides details of how an API consumer requests an access token. Please refer to Identity and Consent Management (https://github.com/camaraproject/IdentityAndConsentManagement/) for the released version of the profile.
    The specific authorization flows to be used will be agreed upon during the onboarding process, happening between the API consumer and the API provider, taking into account the declared purpose for accessing the API, whilst also being subject to the prevailing legal framework dictated by local legislation.
    In cases where personal data is processed by the API and users can exercise their rights through mechanisms such as opt-in and/or opt-out, the use of three-legged access tokens is mandatory. This ensures that the API remains in compliance with privacy regulations, upholding the principles of transparency and user-centric privacy-by-design.

  version: 0.1.0-rc.1

  x-camara-commonalities: 0.6
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
externalDocs:
  description: Product documentation at CAMARA
  url: https://github.com/camaraproject/SubscriptionStatus
servers:
  - url: "{apiRoot}/subscription-status/v0.1rc1"
    variables:
      apiRoot:
        default: http://localhost:9091
        description: API root defined by the provider (e.g., `api.example.com`).

paths:
  /retrive-subscription-status:
    post:
      security:
        - openId:
            - subscription-status:retrive-subscription-status
      tags:
        - Retrive Subscription Status
      description: |
        Obtain the business subscription status of the provided phone number, including Voice/SMS inbound, Voice/SMS outbound, and data service status.
      operationId: retriveSubscriptionStatus
      summary: Retrieve subscription status of a phone number
      parameters:
        - $ref: "#/components/parameters/x-correlator"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SubscriptionStatusRequest"
            examples:
              Three-Legged Without Phone Number Example:
                value: {}
              Two-Legged and Three-leg Access Token Example:
                value:
                  phoneNumber: "+346661113334"
      responses:
        "200":
          description: Subscription status retrieved successfully
          headers:
            x-correlator:
              $ref: "#/components/headers/x-correlator"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SubscriptionStatusResponse"
        "400":
          $ref: "#/components/responses/Generic400"
        "401":
          $ref: "#/components/responses/Generic401"
        "403":
          $ref: "#/components/responses/Generic403"
        "404":
          $ref: "#/components/responses/Generic404"
        "422":
          $ref: "#/components/responses/Generic422"

components:
  securitySchemes:
    openId:
      type: openIdConnect
      openIdConnectUrl: https://example.com/.well-known/openid-configuration
  parameters:
    x-correlator:
      name: x-correlator
      in: header
      description: Correlation ID for cross-service tracking
      schema:
        $ref: "#/components/schemas/XCorrelator"
  headers:
    x-correlator:
      description: Correlation id for the different services
      schema:
        $ref: "#/components/schemas/XCorrelator"
  schemas:
    XCorrelator:
      type: string
      pattern: ^[a-zA-Z0-9-_:;.\/<>{}]{0,256}$
      example: "b4333c46-49c0-4f62-80d7-f0ef930f1c46"
    SubscriptionStatusRequest:
      type: object
      properties:
        phoneNumber:
          $ref: "#/components/schemas/PhoneNumber"
    SubscriptionStatusResponse:
      type: object
      required:
        - voiceSmsIn
        - voiceSmsOut
        - dataService
      properties:
        voiceSmsIn:
          type: string
          enum: [active, suspended]
          description: Status of inbound Voice/SMS services
        voiceSmsOut:
          type: string
          enum: [active, suspended]
          description: Status of outbound Voice/SMS services
        dataService:
          type: string
          enum: [active, suspended, throttled]
          description: Status of mobile data service
    PhoneNumber:
      type: string
      pattern: "^\\+[1-9][0-9]{4,14}$"
      example: "+8613800138000"
      description: E.164 formatted phone number
    ErrorInfo:
      type: object
      required:
        - status
        - code
        - message
      properties:
        status:
          type: integer
          description: HTTP response status code
        code:
          type: string
          description: Code given to this error
        message:
          type: string
          description: Detailed error description
  responses:
    Generic400:
      description: Bad Request
      headers:
        x-correlator:
          $ref: "#/components/headers/x-correlator"
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/ErrorInfo"
              - type: object
                properties:
                  status:
                    enum:
                      - 400
                  code:
                    enum:
                      - INVALID_ARGUMENT
          examples:
            GENERIC_400_INVALID_ARGUMENT:
              description: Invalid Argument. Generic Syntax Exception
              value:
                status: 400
                code: INVALID_ARGUMENT
                message: Client specified an invalid argument, request body or query param.

    Generic401:
      description: Unauthorized
      headers:
        x-correlator:
          $ref: "#/components/headers/x-correlator"
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/ErrorInfo"
              - type: object
                properties:
                  status:
                    enum:
                      - 401
                  code:
                    enum:
                      - UNAUTHENTICATED
          examples:
            GENERIC_401_UNAUTHENTICATED:
              description: Request cannot be authenticated and a new authentication is required
              value:
                status: 401
                code: UNAUTHENTICATED
                message: Request not authenticated due to missing, invalid, or expired credentials. A new authentication is required.

    Generic403:
      description: Forbidden
      headers:
        x-correlator:
          $ref: "#/components/headers/x-correlator"
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/ErrorInfo"
              - type: object
                properties:
                  status:
                    enum:
                      - 403
                  code:
                    enum:
                      - PERMISSION_DENIED
                      - INVALID_TOKEN_CONTEXT
          examples:
            GENERIC_403_PERMISSION_DENIED:
              description: Permission denied. OAuth2 token access does not have the required scope or when the user fails operational security
              value:
                status: 403
                code: PERMISSION_DENIED
                message: Client does not have sufficient permissions to perform this action.
            GENERIC_403_INVALID_TOKEN_CONTEXT:
              description: Reflect some inconsistency between information in some field of the API and the related OAuth2 Token
              value:
                status: 403
                code: INVALID_TOKEN_CONTEXT
                message: "phoneNumber is not consistent with access token."

    Generic404:
      description: Not found
      headers:
        x-correlator:
          $ref: "#/components/headers/x-correlator"
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/ErrorInfo"
              - type: object
                properties:
                  status:
                    enum:
                      - 404
                  code:
                    enum:
                      - IDENTIFIER_NOT_FOUND
          examples:
            GENERIC_404_IDENTIFIER_NOT_FOUND:
              description: The phone number is not associated with a CSP customer account
              value:
                status: 404
                code: IDENTIFIER_NOT_FOUND
                message: The phone number provided is not associated with a customer account

    Generic422:
      description: Unprocessable Content
      headers:
        x-correlator:
          $ref: "#/components/headers/x-correlator"
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/ErrorInfo"
              - type: object
                properties:
                  status:
                    enum:
                      - 422
                  code:
                    enum:
                      - SERVICE_NOT_APPLICABLE
                      - MISSING_IDENTIFIER
                      - UNNECESSARY_IDENTIFIER
          examples:
            GENERIC_422_SERVICE_NOT_APPLICABLE:
              description: Service is not applicable for the provided phone number
              value:
                status: 422
                code: SERVICE_NOT_APPLICABLE
                message: The service is not applicable for the provided phone number
            GENERIC_422_MISSING_IDENTIFIER:
              description: No phone number has been provided either explicitly or associated with the access token
              value:
                status: 422
                code: MISSING_IDENTIFIER
                message: No phone number has been provided
            GENERIC_422_UNNECESSARY_IDENTIFIER:
              description: An explicit phone number has been provided when one is already associated with the access token
              value:
                status: 422
                code: UNNECESSARY_IDENTIFIER
                message: An explicit phone number has been provided when one is already associated with the access token
